name: Build & Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  push-to-registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Free disk space on Ubuntu runner 🔧
        uses: kfir4444/free-disk-space@main
        with:
          # frees about 6 GB, warning: may remove required tools
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: true
      - name: Push to Docker Hub
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: higgsfield/pytorch:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
