name: Build & Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  push-to-registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Verify Dockerfile changed
        uses: tj-actions/changed-files@v14.1
        id: changed_files
        with:
          files: |
            Dockerfile
      - name: Set up Docker Buildx
        if: steps.changed_files.outputs.any_changed  == 'true'
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        if: steps.changed_files.outputs.any_changed  == 'true'
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx- 
      - name: Log in to Docker Hub
        if: steps.changed_files.outputs.any_changed  == 'true'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        if: steps.changed_files.outputs.any_changed  == 'true'
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: higgsfield/pytorch:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
